ecs_cluster_name = "jeremy-ecs-cluster-prod"
ecs_service_name = "jeremy-ecs-service-prod"
ecs_task_defn_family = "jeremy-ecs-task-def-prod"
ecs_container_name = "jeremy-container-prod"
ecs_port_name = "jeremy-3000-tcp-prod"