ecs_cluster_name = "jeremy-ecs-cluster-uat"
ecs_service_name = "jeremy-ecs-service-uat"
ecs_task_defn_family = "jeremy-ecs-task-def-uat"
ecs_container_name = "jeremy-container-uat"
ecs_port_name = "jeremy-3000-tcp-uat"